# Generated by Django 5.1.3 on 2024-11-20 19:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('cpf', models.CharField(max_length=12, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('rua', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=8)),
                ('bairro', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Em produção', 'Em produção'), ('Em entrega', 'Em entrega'), ('Concluído', 'Concluído')], default='Pendente', max_length=150)),
                ('valor_entrega', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usuarioFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_usuarioFK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Salada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=500)),
                ('calorias', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso', models.IntegerField()),
                ('rendimento', models.IntegerField()),
                ('categoria', models.CharField(choices=[('Clássicas', 'Clássicas'), ('Proteicas', 'Proteicas'), ('Veganas', 'Veganas'), ('Low Carb', 'Low Carb'), ('Detox', 'Detox'), ('Agridoces', 'Agridoces')], max_length=100)),
                ('avaliacao', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('foto', models.FileField(blank=True, null=True, upload_to='fotos_saladas')),
                ('ingredientes', models.ManyToManyField(to='app.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('observacao', models.CharField(blank=True, max_length=300, null=True)),
                ('pedidoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemPedido_pedidoFK', to='app.pedido')),
                ('saladaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemPedido_saladaFK', to='app.salada')),
            ],
        ),
        migrations.CreateModel(
            name='Salada_Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soma_avaliacao', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_avaliacoes', models.BigIntegerField()),
                ('saladaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saladaAvaliacao_saladaFK', to='app.salada')),
            ],
        ),
    ]
