# Generated by Django 5.1.3 on 2024-11-20 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Em produção', 'Em produção'), ('Em entrega', 'Em entrega'), ('Concluído', 'Concluído')], max_length=150)),
                ('valor_entrega', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usuarioFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_usuarioFK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Salada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=500)),
                ('calorias', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso', models.IntegerField()),
                ('rendimento', models.IntegerField()),
                ('categoria', models.CharField(choices=[('Clássicas', 'Clássicas'), ('Proteicas', 'Proteicas'), ('Veganas', 'Veganas'), ('Low Carb', 'Low Carb'), ('Detox', 'Detox'), ('Agridoces', 'Agridoces')], max_length=100)),
                ('ingredientes', models.ManyToManyField(to='app.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedidoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemPedido_pedidoFK', to='app.pedido')),
                ('saladaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemPedido_saladaFK', to='app.salada')),
            ],
        ),
        migrations.CreateModel(
            name='Salada_Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soma_avaliacao', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_avaliacoes', models.BigIntegerField()),
                ('saladaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saladaAvaliacao_saladaFK', to='app.salada')),
            ],
        ),
    ]
