# Generated by Django 5.1.3 on 2024-11-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ingrediente_pedido_salada_item_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_pedido',
            name='quantidade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
