# Generated by Django 5.1.3 on 2024-11-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_pedido_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_pedido',
            name='observacao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
