# Generated by Django 5.1.3 on 2024-11-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_item_pedido_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='salada',
            name='avaliacao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
